fileshare/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views
from django.contrib.auth import urls
from .views import register

urlpatterns = [
	url(r'^register/$', register, name='register'),
    # Login
    url(r'^login/$', views.login, {'template_name': 'accounts/login.html'}, name='login'), 
    url(r'^logout/$', views.logout_then_login, {'login_url': 'core:index'}, name='logout'),
]

fileshare/core/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^login/$', login, name='login'),
]

fileshare/share/urls.py
from django.conf.urls import url
#from . import views
from .views import *

urlpatterns = [
	# File
	url(r'^file/list/$', FileList.as_view(), name='file_list'),
	url(r'^file/add/$', FileCreate.as_view(), name='file_add'),
	url(r'^file/details/(?P<pk>[0-9]+)/$', FileDetail.as_view(), name='file_details'),
	url(r'^file/(?P<pk>[0-9]+)/delete/$', FileDelete.as_view(), name='file_delete'),
]

fileshare/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#Import URL's
from fileshare.core import urls as core_urls 
from fileshare.share import urls as share_urls
from fileshare.accounts import urls as accounts_urls
urlpatterns = [
    url(r'^', include(core_urls, namespace='core')),
    url(r'^share/', include(share_urls, namespace='share')),
    url(r'^accounts/', include(accounts_urls, namespace='accounts')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fileshare/accounts/models.py
from django.db import models

# Create your models here.

fileshare/core/models.py
from django.db import models

# Create your models here.

fileshare/share/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

# Create your models here.

class File(models.Model):
	user = models.ForeignKey(User, verbose_name='Usuário', related_name='users', on_delete=models.CASCADE)
	description = models.CharField('Descrição', max_length=200, null=True, blank=True)
	publication_date = models.DateField('Data de Publicação')
	created_at = models.DateTimeField('Criado em', auto_now_add=True)
	update_at = models.DateTimeField('Atualizado em', auto_now_add=True)
	published = models.BooleanField()
	file = models.FileField('Arquivo', upload_to='upload/file')

	def __str__(self):
		return self.description

	def get_absolute_url(self):
		return reverse('share:file_list')

fileshare/share/forms.py
from django import forms
from .models import *
from datetime import date

class FileForm(forms.ModelForm):
	class Meta:
		model = File
		exclude = ['created_at', 'update_at', 'user']

fileshare/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.conf import settings
# Create your views here.


def register(request):
	template_name = 'accounts/register.html'
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			user = authenticate(
				username=user.username, password=form.cleaned_data['password1'])
			login(request, user)
			return redirect('core:index')
	else:
		form = UserCreationForm()
	context = {
		'form': form
	}
	return render(request, template_name, context)

fileshare/core/views.py
from django.shortcuts import render
from fileshare.share.models import File
# Create your views here.

def index(request):
	list_f = File.objects.all().order_by('-created_at')
	return render(request, 'index.html', {'list_files': list_f})

def login(request):
	return render(request, 'login.html')

fileshare/share/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.core.urlresolvers import  reverse, reverse_lazy
from django.contrib import messages
from .models import *
from datetime import date
from .forms import *
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required

# Create your views here.


# File CRUD
class FileList(ListView):

	paginate_by = 50

	model = File
	template_name = 'file/list.html'

	def get_queryset(self):
		self.queryset = super(FileList, self).get_queryset()
		if self.request.GET.get('search_box', False):
			self.queryset=self.queryset.filter(description__icontains = self.request.GET['search_box'])
		return self.queryset

class FileDetail(DetailView):
	model = File
	template_name = 'file/details.html'

class FileCreate(CreateView):
	model = File
	template_name = 'file/add.html'
	form_class = FileForm
	def form_valid(self,form):
		self.object = form.save(commit=False)
		self.object.user = self.request.user
		self.object.save()
		return HttpResponseRedirect(self.get_success_url())

class FileUpdate(UpdateView):
	model = File
	template_name = 'file/add.html'
	form_class = FileForm
	success_url = reverse_lazy('share:file_list')

class FileDelete(DeleteView):
	model = File
	success_url = reverse_lazy('share:file_list')

# End File

fileshare/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}

<section id="login">
    <div class="container">
    	<div class="row">
    	    <div class="col-xs-12">
        	    <div class="form-wrap">
                <h1>Faça login com sua conta de e-mail</h1>
                    <form role="form" method="post" id="login-form" autocomplete="off">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    {% endfor %}
                        <div class="checkbox">
                            <span class="character-checkbox" onclick="showPassword()"></span>
                            <span class="label">Mostrar senha</span>
                        </div>
                        <button type="submit" id="btn-login" class="btn btn-custom btn-lg btn-block">Login</button>

                    </form>
                    <a href="javascript:;" class="forget" data-toggle="modal" data-target=".forget-modal">Esqueceu a senha?</a>
                    <a href="{% url 'accounts:register' %}" class="forget">Cadastre-se</a>
                    <hr>
        	    </div>
    		</div> <!-- /.col-xs-12 -->
    	</div> <!-- /.row -->
    </div> <!-- /.container -->
</section>

<div class="modal fade forget-modal" tabindex="-1" role="dialog" aria-labelledby="myForgetModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">×</span>
					<span class="sr-only">Fechar</span>
				</button>
				<h4 class="modal-title">Recuperar senha</h4>
			</div>
			<div class="modal-body">
				<p>Digite o email da sua conta</p>
				<input type="email" name="recovery-email" id="recovery-email" class="form-control" autocomplete="off">
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<button type="button" class="btn btn-custom">Recuperar</button>
			</div>
		</div> <!-- /.modal-content -->
	</div> <!-- /.modal-dialog -->
</div> <!-- /.modal -->
{% endblock %}

fileshare/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}

<section id="login">
    <div class="container">
    	<div class="row">
    	    <div class="col-xs-12">
        	    <div class="form-wrap">
                <h1>Informe seus dados</h1>
                    <form role="form" method="post" id="login-form" autocomplete="off">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                        {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                        {% endfor %}
                        <button type="submit" id="btn-login" class="btn btn-custom btn-lg btn-block">Cadastrar</button>

                    </form>
                    <hr>
        	    </div>
    		</div> <!-- /.col-xs-12 -->
    	</div> <!-- /.row -->
    </div> <!-- /.container -->
</section>
{% endblock %}

fileshare/core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datepicker.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datetimepicker.css' %}">


	<link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-login.css' %}">


    <style type="text/css">

  </style>
	
	<title>Sistema de Compartilhamento de Arquivos</title>
</head>
<body>
	<!-- NAVBAR -->
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<!-- add if de admin / usuario -->
		<div class="container-fluid">
			<!-- agrupar para mobile -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<p class="navbar-brand hidden-md hidden-sm">
					
				</p>
			</div>
			<!-- links da navbar -->
			<div class="collapse navbar-collapse navbar-ex1-collapse">

				<!-- ícone na navbar -->
				{% include "navbar_user.html" %}
			</div><!-- /.navbar-collapse -->
		</div>
	</nav>
	<!-- NAVBAR -->

	<!-- Mensagens -->
	<div class="container">
    	<div class="row">
        	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				{% if messages %}
			        {% for message in messages %}
			        <div class="alert alert-info">
						<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
						<strong>Atenção</strong> 
			        	<p>{{ message }}</p>
					</div>
			        {% endfor %}
				{% endif %}
			</div>
		</div>
	</div>

	{% block body %}

	{% endblock %}
	{% block scripts %}
	<script type="text/javascript" src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.form.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.cicle.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.easing.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap-login.js' %}"></script>
	{% endblock %}
</body>
</html>

fileshare/core/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="container container-body">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <p class="header-title">
        || Últimos arquivos upados
      </p>
        {% if user.is_authenticated %}
        {% for list in list_files %}
        <ul>
        <li><a href="{% url 'share:file_details' list.id %}">{{ list.description }}</a></li>
        </ul>
        {% endfor %}
        {% else %}
        <li><a href="{% url 'accounts:login' %}">Logue-se para ter acesso ao sistema.</a></li>
        {% endif %}
    </div>
  </div>
  
</div>

{% endblock %}

fileshare/core/templates/navbar_user.html
	<ul class="nav navbar-nav navbar-nav-cent">
		<li><a href="{% url 'core:index' %}"><p class="fa fa-home"></p> Início</a></li>
		{% if user.is_authenticated %}
		<li><a href="{% url 'share:file_list' %}"><p class="fa fa-file-text"></p> Arquivos</a></li>
		{% endif %}
	</ul>
	<ul class="nav navbar-nav pull-right">
	{% if user.is_authenticated %}
	  <li class="dropdown">
	    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	      <i class="fa fa-lock" aria-hidden="true"></i>
	      Logado como: {{ user.username }}
	      <b class="caret"></b>
	    </a>
	  </li>
		<li>
			<a href="{% url 'accounts:logout' %}">
				<p class="fa fa-sign-out" aria-hidden="true"></p> Sair
			</a>
		</li>
	</ul>
	<ul class="nav navbar-nav pull-right">
	{% else %}
		<li>
			<a href="{% url 'accounts:login' %}">
				<p class="fa fa-sign-out" aria-hidden="true"></p> Entrar
			</a>
		</li>
	</ul>
	{% endif %}

fileshare/share/templates/file/add.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
<nav class="navbar navbar-default navbar-margin">
	<div class="container">
		<a class="navbar-brand" href="#">Cadastro/Alteração dos Arquivos</a>
		<ul class="nav navbar-nav pull-right">
			<li>
				<p class="navbar-btn">
					<a class="btn btn-default" href="{% url 'share:file_list' %}"> 
						<i class="fa fa-times" aria-hidden="true"></i>
						Cancelar
					</a>
				</p>
			</li>
		</ul>
	</div>
</nav>

<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
			<form action="." class="form-group" method="post" enctype="multipart/form-data">{% csrf_token %}
				<fieldset>
					{% for field in form %}
					{% if field.errors %}
					<div class="form-group error" >
						<label class="control-label" >{{ field.label }}</label>
						{{ field|add_class:"form-control input-md" }}
						{% for error in field.errors%}
						<span class="help-inline error">{{ error}}</span>
						{% endfor%}
					</div>
					{%else%}
					<div class="form-group">
						<label class="control-label" >{{ field.label }}</label>
						{% if field.label == "Data de Publicação" %}
							<div class="input-group date datepicker">
							{{ field|add_class:"form-control input-md" }}
		                    <span class="input-group-addon">
		                        <span class="glyphicon glyphicon-calendar"></span>
		                    </span>
		                    </div>
						{% else %}
							{{ field|add_class:"form-control input-md" }}
						{% endif %}
					</div>
					{%endif%}
					{% endfor %}
					<div class="form-group">
						<button type="submit" value="Salvar" class="btn btn-primary">
							<span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
							Salvar
						</button>
					</div>
				</fieldset>
			</form>
		</div>
	</div>
</div>

{% endblock %}


{% block scripts %}

{{ block.super }}

<script>
$(".datepicker").datepicker({
	    format: "yyyy-mm-dd",
		todayBtn: "linked",
		language: "en",
		autoclose: true,
		todayHighlight: true
	  });
</script>

{% endblock %}

fileshare/share/templates/file/details.html
{% extends 'base.html' %}

{% block body %}

<nav class="navbar navbar-default navbar-margin">
  <div class="container">
    <a class="navbar-brand" href="#">Dados do Arquivo</a>
    <ul class="nav navbar-nav pull-right">
      <li>
        <p class="navbar-btn">
          <a class="btn btn-default nav-dist-btn" href="{% url 'share:file_list' %}"> 
            <i class="fa fa-chevron-left" aria-hidden="true"></i>
            Voltar
          </a>
        </p>
      </li>
    </ul>
  </div>
</nav>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <p>
          <strong>Descrição:</strong>
          {{ object.description }}
        </p>
        <p>
          <strong>Data:</strong>
          {{ object.publication_date }}
        </p>
        <p>
          <strong>Publicado:</strong>
          {% if object.published %}
              <td>Sim</td>
          {% else %}
              <td>Não</td>
          {% endif %}
        </p>
        <p>
          <strong>Upado por:</strong>
          {{ object.user.username }}
        </p>
        <p>
          <strong>Link:</strong>
          <a href="/media/{{object.file}}" class="btn btn-primary">
            <i class="fa fa-arrow-circle-down" aria-hidden="true"></i>
            Download
          </a>
        </p>
        
      </div>
    </div>
  </div>

  {% endblock %}

fileshare/share/templates/file/list.html
{% extends 'base.html' %}
{% block body %}

<nav class="navbar navbar-default navbar-margin">
	<div class="container">
		<!-- Form Search -->
		<div class="row">
			<ul class="nav nav-inline">
				<li>
					<div class="col-md-8 col-xs-8 col-sm-8 space-top">
						<form class="form-horizontal" action="." method="get">
							<div class="input-group">
								<input id="search_box" name="search_box" type="text" placeholder="Informe a descrição do arquivo" class="form-control" autofocus="true" value="{{ request.GET.search_box }}">
								<span class="input-group-btn">
									<button type="submit" class="btn btn-default form-control" title="Clique para realizar a pesquisar">
										<i class="fa fa-search" aria-hidden="true"></i>
									</button>
								</span>
							</div>
						</form>
					</div>
				</li>
				<li>
					<div class="col-md-4 col-xs-4 col-sm-4 space-top">
						<a class="btn btn-default pull-right" href="{% url 'share:file_add' %}"> 
							<i class="fa fa-file-o" aria-hidden="true"></i>
							Novo
						</a>
					</div>
				</li>
			</ul>
		</div>
	</div>
</nav>


<div class="container">
	<div class="row">
	{% if object_list.count > 0 %}
		<div class="col-lg-12">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Descrição</th>
						<th>Publicado</th>
						<th>Upado por</th>
						<th style="width: 145px;">Ações</th>
					</tr>
				</thead>
				<tbody>
					{% for file in object_list %}
					<tr>
						<td>{{ file.description|slice:":25" }}</td>
						{% if file.published %}
							<td>Sim</td>
						{% else %}
							<td>Não</td>
						{% endif %}
						<td> {{ file.user.username }}</td>
						<td>                    
							<a href="{% url 'share:file_details' file.id %}" class="btn btn-default" title="Exibir">
								<i class="fa fa-eye" aria-hidden="true"></i>
							</a>

							<a href="/media/{{file.file}}" class="btn btn-default" title="Baixar">
								<i class="fa fa-download" aria-hidden="true"></i>
							</a>

							<a href="#modal-id-{{ file.id }}" class="btn btn-default" title="Remover" data-toggle="modal">
								<i class="fa fa-trash-o" aria-hidden="true"></i>
							</a>
						</td>
					</tr>

					<!-- MODAL -->
					<div class="col-xs-12 col-sm-12 col-md-10 col-lg-10">
						<div class="modal fade" id="modal-id-{{ file.id }}">
							<div class="modal-dialog">
								<div class="modal-content">
									<div class="modal-header">
										<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
										<h4 class="modal-title">Alerta!</h4>
									</div>
									<div class="modal-body">
										<p>Deseja realmente remover essa ata: <strong>{{ file.title }}</strong>?</p>
									</div>
									<div class="modal-footer">
										<form action="{% url 'share:file_delete' file.pk %}" method="post">{%csrf_token%}
											<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
											<button type="submit" class='btn btn-danger' title='Deletar'>
												Delete
											</button>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- /MODAL -->
					{% endfor %}
				</tbody>
			</table>
		</div>
	{% else %}
		<p><center>Não há documentos registrados.</center></p>
	{% endif %}
	</div>
	<center>
		<!-- Paginação -->
		{% if page_obj.has_other_pages %}
		<nav>
			<ul class="pagination">
				{% if page_obj.has_previous %}
				<li>
					<a href="?page={{ page_obj.previous_page_number }}{% if request.GET.search_box %}&search_box={{ request.GET.search_box }}{% endif %}" aria-label="Previous">
						<span aria-hidden="true">&laquo;</span>
					</a>
				</li>
				{% else %}
				<li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
				{% endif %}
				{% for page_num in page_obj.paginator.page_range %}
				<li {% if page_num == patients.number %} class="active" {% endif %}>
					<a href="?page={{ page_num }}{% if request.GET.search_box %}&search_box={{ request.GET.search_box }}{% endif %}">{{ page_num }}</a>
				</li>
				{% endfor %}
				{% if page_obj.has_next %}
				<li>
					<a href="?page={{ page_obj.next_page_number}}{% if request.GET.search_box %}&search_box={{ request.GET.search_box }}{% endif %}" aria-label="Next">
						<span aria-hidden="true">&raquo;</span>
					</a>
				</li>
				{% else %}
				<li class="disabled">
					<a href="#" aria-label="Next">
						<span aria-hidden="true">&raquo;</span>
					</a>
				</li>
				{% endif %}
			</ul>
		</nav>
		{% endif %}
		<!-- Fim da Paginação -->
	</center>
</div>

{% endblock %}